package com.amazonaws.mobilehelper.auth.signin.ui.buttons;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//

/**
 * Sign-in Button Attributes
 */
/* package */ class SignInButtonAttributes {
    private int cornerRadius;
    private int backgroundColor;
    private int backgroundColorPressed;
    private int topShadowColor;
    private int bottomShadowColor;
    private int topShadowThickness;
    private int bottomShadowThickness;
    private int textColor;
    private int defaultTextResourceId;
    private int imageIconResourceId;

    /* package */ int getCornerRadius() {
        return cornerRadius;
    }

    /* package */ int getBackgroundColor() {
        return backgroundColor;
    }

    /* package */ int getBackgroundColorPressed() {
        return backgroundColorPressed;
    }

    /* package */ int getTopShadowColor() {
        return topShadowColor;
    }

    /* package */ int getBottomShadowColor() {
        return bottomShadowColor;
    }

    /* package */ int getTopShadowThickness() {
        return topShadowThickness;
    }

    /* package */ int getBottomShadowThickness() {
        return bottomShadowThickness;
    }

    /* package */ int getTextColor() {
        return textColor;
    }

    /* package */ int getDefaultTextResourceId() {
        return defaultTextResourceId;
    }

    /* package */ int getImageIconResourceId() {
        return imageIconResourceId;
    }

    /* package */ SignInButtonAttributes withCornerRadius(int cornerRadius) {
        this.cornerRadius = cornerRadius;
        return this;
    }

    /* package */ SignInButtonAttributes withBackgroundColor(int backgroundColor) {
        this.backgroundColor = backgroundColor;
        return this;
    }

    /* package */ SignInButtonAttributes withBackgroundColorPressed(int backgroundColorPressed) {
        this.backgroundColorPressed = backgroundColorPressed;
        return this;
    }

    /* package */ SignInButtonAttributes withTopShadowColor(int topShadowColor) {
        this.topShadowColor = topShadowColor;
        return this;
    }

    /* package */ SignInButtonAttributes withBottomShadowColor(int bottomShadowColor) {
        this.bottomShadowColor = bottomShadowColor;
        return this;
    }

    /* package */ SignInButtonAttributes withTopShadowThickness(int topShadowThickness) {
        this.topShadowThickness = topShadowThickness;
        return this;
    }

    /* package */ SignInButtonAttributes withBottomShadowThickness(int bottomShadowThickness) {
        this.bottomShadowThickness = bottomShadowThickness;
        return this;
    }

    /* package */ SignInButtonAttributes withTextColor(int textColor) {
        this.textColor = textColor;
        return this;
    }

    /* package */ SignInButtonAttributes withDefaultTextResourceId(int defaultTextResourceId) {
        this.defaultTextResourceId = defaultTextResourceId;
        return this;
    }

    /* package */ SignInButtonAttributes withImageIconResourceId(int imageIconResourceId) {
        this.imageIconResourceId = imageIconResourceId;
        return this;
    }
}
