# Gradle config for "Large" Circle CI resource (https://circleci.com/pricing/price-list/)

org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dkotlin.daemon.jvm.options=-Xmx1024m
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.workers.max=4
test.heap.max=2g
