package com.amazonaws.mobilehelper.auth;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//

/**
 * Allows the application to get an asynchronous response with user's
 * unique identifier.
 */
public interface IdentityHandler {
    /**
     * Handles the user's unique identifier.
     * @param identityId Amazon Cognito Identity ID which uniquely identifies
     *                   the user.
     */
    void onIdentityId(final String identityId);

    /**
     * Handles any error that might have occurred while getting the user's
     * unique identifier from Amazon Cognito.
     * @param exception exception
     */
    void handleError(final Exception exception);
}
