package com.amazonaws.mobilehelper.auth;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//

/**
 * Supported Provider Types
 */
public enum IdentityProviderType {

    /**
     * Facebook
     */
    FACEBOOK,

    /**
     * Google
     */
    GOOGLE,

    /**
     * Twitter
     */
    TWITTER,

    /**
     * Amazon
     */
    AMAZON,

    /**
     * Custom SAML Provider
     */
    CUSTOM_SAML,

    /**
     * Cognito User Pool
     */
    COGNITO_USER_POOL;
}
