package com.amazonaws.mobilehelper.auth.signin;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//

/**
 * Interface for handling permissions
 */
public interface SignInPermissionsHandler {
    /**
     * @return the permission request code that will be used by this provider.
     */
    int getPermissionRequestCode();

    /**
     * Handler for permissions results.
     *
     * @param requestCode the permissions request code
     * @param permissions the permissions requested
     * @param grantResults the results.
     */
    void handleRequestPermissionsResult(int requestCode, String permissions[],
                                        int[] grantResults);
}
