//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//
package org.odk.collect.android.amazonaws.mobile;

import android.graphics.Color;

import com.amazonaws.mobilehelper.config.AWSMobileHelperConfiguration;
import com.amazonaws.regions.Regions;

import org.odk.collect.android.BuildConfig;


/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT = BuildConfig.AWS_MOBILEHUB_USER_AGENT;
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION = Regions.fromName(BuildConfig.AMAZON_COGNITO_REGION);
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID = BuildConfig.AMAZON_COGNITO_IDENTITY_POOL_ID;
    public static final Regions AMAZON_DYNAMODB_REGION = Regions.fromName(BuildConfig.AMAZON_DYNAMODB_REGION);

    private static final AWSMobileHelperConfiguration helperConfiguration = new AWSMobileHelperConfiguration.Builder()
        .withCognitoRegion(AMAZON_COGNITO_REGION)
        .withCognitoIdentityPoolId(AMAZON_COGNITO_IDENTITY_POOL_ID)
        .build();
    /**
     * @return the configuration for AWSKit.
     */
    public static AWSMobileHelperConfiguration getAWSMobileHelperConfiguration() {
        return helperConfiguration;
    }
}
