/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.google.android.odk;

public final class R {
    public static final class anim {
        public static final int fade_in=0x7f040000;
        public static final int fade_out=0x7f040001;
        public static final int push_left_in=0x7f040002;
        public static final int push_left_out=0x7f040003;
        public static final int push_right_in=0x7f040004;
        public static final int push_right_out=0x7f040005;
        public static final int start_arrow=0x7f040006;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int left_arrow=0x7f020000;
        public static final int paper_icon=0x7f020001;
    }
    public static final class id {
        public static final int add_url=0x7f060001;
        public static final int add_url_title=0x7f060000;
        public static final int chooseform=0x7f060008;
        public static final int description=0x7f060005;
        public static final int formchooser_message=0x7f060002;
        public static final int formmanager_message=0x7f060007;
        public static final int manageform=0x7f06000a;
        public static final int progressbar=0x7f060004;
        public static final int rl=0x7f060003;
        public static final int senddata=0x7f060009;
        public static final int submit=0x7f060006;
    }
    public static final class layout {
        public static final int add_form=0x7f030000;
        public static final int formchooser=0x7f030001;
        public static final int formentry=0x7f030002;
        public static final int formentry_end=0x7f030003;
        public static final int formentry_start=0x7f030004;
        public static final int formmanager=0x7f030005;
        public static final int mainmenu=0x7f030006;
    }
    public static final class string {
        public static final int add_another_repeat=0x7f050012;
        public static final int add_form=0x7f050030;
        public static final int add_repeat=0x7f050011;
        public static final int app_name=0x7f050000;
        public static final int cancel=0x7f05002f;
        public static final int change_language=0x7f050033;
        public static final int choose_form=0x7f05000a;
        public static final int clear_answer=0x7f050032;
        public static final int data_saved_error=0x7f050025;
        public static final int data_saved_ok=0x7f050024;
        public static final int delete_confirm=0x7f050029;
        public static final int delete_error=0x7f05001c;
        public static final int delete_form=0x7f050031;
        public static final int directory_error=0x7f050021;
        public static final int enter_data=0x7f050004;
        public static final int enter_data_description=0x7f050006;
        public static final int enter_data_message=0x7f050005;
        public static final int enter_url=0x7f05000f;
        public static final int entryquit_confirm=0x7f05002a;
        public static final int form=0x7f050001;
        public static final int form_added_ok=0x7f050023;
        public static final int form_deleted_error=0x7f050028;
        public static final int form_deleted_ok=0x7f050022;
        public static final int form_load_error=0x7f050016;
        public static final int get_image=0x7f050015;
        public static final int get_location=0x7f050013;
        public static final int getting_location=0x7f050014;
        public static final int gps_disabled_error=0x7f050017;
        public static final int invalid_answer_error=0x7f050019;
        public static final int languages_error=0x7f05001d;
        public static final int load_error=0x7f050020;
        public static final int loading_form=0x7f05000b;
        public static final int main_menu=0x7f050002;
        public static final int main_menu_message=0x7f050003;
        public static final int manage_data=0x7f050008;
        public static final int manage_forms=0x7f050009;
        public static final int no=0x7f05002d;
        public static final int no_answer_error=0x7f050026;
        public static final int no_forms_error=0x7f05001a;
        public static final int ok=0x7f05002e;
        public static final int preferences=0x7f050010;
        public static final int questionview_error=0x7f05001b;
        public static final int readonly_answer_error=0x7f050027;
        public static final int required_answer_error=0x7f050018;
        public static final int save_data=0x7f05000c;
        public static final int save_data_description=0x7f05000e;
        public static final int save_data_message=0x7f05000d;
        public static final int sdcard_error=0x7f05001e;
        public static final int send_data=0x7f050007;
        public static final int settings=0x7f05002b;
        public static final int url_error=0x7f05001f;
        public static final int yes=0x7f05002c;
    }
}
