package com.amazonaws.mobilehelper.auth.signin.ui;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//

import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.ColorFilter;
import android.graphics.Paint;
import android.graphics.PixelFormat;
import android.graphics.Rect;
import android.graphics.drawable.Drawable;
import android.support.annotation.IntRange;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/**
 * Provides drawable for a vertically split background.
 */
public class SplitBackgroundDrawable extends Drawable {
    private Paint paint;
    private int distanceFromTopToSplitPoint = -1;
    private int topBackgroundColor;

    public SplitBackgroundDrawable(int distanceFromTop, int topBackgroundColor) {
        paint = new Paint();
        this.topBackgroundColor = topBackgroundColor;
        setSplitPointDistanceFromTop(distanceFromTop);
    }

    public void setSplitPointDistanceFromTop(int distanceFromTop) {
        distanceFromTopToSplitPoint = distanceFromTop;

        invalidateSelf();
    }

    @Override
    public void draw(@NonNull final Canvas canvas) {
        final Rect b = getBounds();
        paint.setColor(topBackgroundColor);
        float y = distanceFromTopToSplitPoint < b.height() ? distanceFromTopToSplitPoint : b.height();

        canvas.drawRect(0, 0, b.width(), y, paint);
        paint.setColor(Color.WHITE);
        canvas.drawRect(0, y, b.width(), b.height(), paint);
    }

    @Override
    public void setAlpha(@IntRange(from = 0, to = 255) final int alpha) {
    }

    @Override
    public void setColorFilter(@Nullable final ColorFilter colorFilter) {
    }

    @Override
    public int getOpacity() {
        return PixelFormat.TRANSLUCENT;
    }
}
